In [2]:
import numpy as np

## Model with 

- $T_{min}$ = 300
- $T_{max}$ = 320
- $N_{replicas}$ = 6
- Division of temperature space: gemetric series 

In [8]:
acceptance = np.load('acceptance1.npy')
Tmin = 300
Tmax = 320
Nreplicas = 6
T = np.geomspace(Tmin, Tmax, Nreplicas)

print(f'Temperatures: \n{T}')
print('Acceptance ratio:')
print(np.diag(acceptance,1) / np.diag(acceptance,-1))
print(f'Acceptance matrix: \n{acceptance}')

Temperatures: 
[300.         303.89741047 307.84545363 311.84478727 315.89607773
 320.        ]
Acceptance ratio:
[0.00920245 0.05521472 0.02167183 0.02312139 0.03809524]
Acceptance matrix: 
[[  0.   3.   3.   5.  12.   7.]
 [326.   0.  18.  10.   7.  15.]
 [350. 326.   0.   7.   3.   2.]
 [337. 317. 323.   0.   8.   7.]
 [337. 369. 357. 346.   0.  12.]
 [338. 340. 341. 278. 315.   0.]]


## Model with 

- $T_{min}$ = 300
- $T_{max}$ = 310
- $N_{replicas}$ = 6
- Division of temperature space: gemetric series 

In [9]:
acceptance = np.load('acceptance2.npy')
Tmin = 300
Tmax = 310
Nreplicas = 6
T = np.geomspace(Tmin, Tmax, Nreplicas)

print(f'Temperatures: \n{T}')
print('Acceptance ratio:')
print(np.diag(acceptance,1) / np.diag(acceptance,-1))
print(f'Acceptance matrix: \n{acceptance}')

Temperatures: 
[300.         301.97385453 303.96069606 305.96061005 307.97368251
 310.        ]
Acceptance ratio:
[0.13544669 0.13109756 0.0955414  0.12461059 0.14730878]
Acceptance matrix: 
[[  0.  47.  39.  46.  53.  46.]
 [347.   0.  43.  39.  51.  33.]
 [345. 328.   0.  30.  42.  32.]
 [321. 360. 314.   0.  40.  59.]
 [341. 311. 324. 321.   0.  52.]
 [342. 328. 335. 330. 353.   0.]]
